name: Pull RFQ Emails (Supabase)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Sanity check secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          set -euo pipefail
          [ -n "${SUPABASE_URL:-}" ] || (echo "Missing SUPABASE_URL" && exit 1)
          [ -n "${SUPABASE_SERVICE_ROLE_KEY:-}" ] || (echo "Missing SUPABASE_SERVICE_ROLE_KEY" && exit 1)

      - name: Call Edge Function (POST, single line)
        shell: bash
        env:
          URL: ${{ secrets.SUPABASE_URL }}/functions/v1/pull-rfq-emails
          KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          BODY: ${{ secrets.FUNCTION_PAYLOAD }}
        run: |
          set -euo pipefail
          echo "Key length: ${#KEY}"   # debería ser > 0
          echo "Curl (headers masked) -> -H Authorization and -H apikey deben verse debajo"
          echo curl -X POST "$URL" -H "Authorization: Bearer ***" -H "apikey: ***" -H "Content-Type: application/json" --data "${BODY:-{}}"
          STATUS=$(curl -sS -o response.json -w "%{http_code}" -X POST "$URL" -H "Authorization: Bearer $KEY" -H "apikey: $KEY" -H "Content-Type: application/json" --data "${BODY:-{}}")
          echo "HTTP Status: $STATUS"
          echo "Response body:"; cat response.json
          [[ "${STATUS:0:1}" == "2" ]]

          # Falla el job si no es 2xx
          if [ "${STATUS:0:1}" != "2" ]; then
            exit 1
          fi
