name: Pull RFQ Emails (Supabase)

on:
  workflow_dispatch: {}   # Lanzar manualmente desde Actions
  schedule:
    # Corre cada 5 minutos (GitHub usa UTC)
    - cron: "*/5 * * * *"

jobs:
  call-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Edge Function (POST)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          FUNCTION_PAYLOAD: ${{ secrets.FUNCTION_PAYLOAD }}
        run: |
          set -euo pipefail
          URL="$SUPABASE_URL/functions/v1/pull-rfq-emails"

          # Llamada POST con cabeceras JWT correctas
          STATUS=$(curl -sS -o response.json -w "%{http_code}" \
            -X POST "$URL" \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY" \
            -H "apikey: $SUPABASE_SERVICE_ROLE_KEY" \
            -H "Content-Type: application/json" \
            --data "${FUNCTION_PAYLOAD:-{}}")

          echo "HTTP Status: $STATUS"
          echo "Response body:"
          cat response.json
          
          # Falla el job si no es 2xx
          if [ "${STATUS:0:1}" != "2" ]; then
            exit 1
          fi
